---

- name: install nginx
  apt:
    name: nginx
    state: present

- name: remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - stop nginx
    - start nginx

- name: copy default nginx configuration
  template:
    src: main.conf
    dest: /etc/nginx/sites-available/main.conf
  notify:
    - stop nginx
    - start nginx

- name: link nginx configuration
  file:
    src: /etc/nginx/sites-available/main.conf
    dest: /etc/nginx/sites-enabled/main
    state: link
  notify:
    - stop nginx
    - start nginx

# Temporary hack until autobencher has it's own provisioning
- name: copy benchmarks nginx configuration
  template:
    src: benchmarks.scikit-bio.org.conf
    dest: /etc/nginx/sites-available/benchmarks.scikit-bio.org.conf

- name: link benchmarks nginx configuration
  file:
    src: /etc/nginx/sites-available/benchmarks.scikit-bio.org.conf
    dest: /etc/nginx/sites-enabled/benchmarks.scikit-bio.org
    state: link
  notify:
    - stop nginx
    - start nginx
