---

- name: ufw open ports
  ufw:
    rule: allow
    state: enabled
    name: "{{ item }}"
  with_items:
    - OpenSSH
    - Nginx Full

- name: ufw allow 2223
  ufw:
    rule: allow
    port: 2223
